on:
  push:
    branches:
      - 'master'
    paths:
      - 'devcontainer/**'
  pull_request:
    branches:
      - 'master'
    paths:
      - 'devcontainer/**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & deploy ``devcontainer`` images
    strategy:
      fail-fast: false
      matrix:
        include:
          - { platform: linux/amd64, arch: x86_64,  label_prefix: amd64   }
          - { platform: linux/arm64, arch: aarch64, label_prefix: aarch64 }
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: eoshep/devcontainer
          tags: |
            type=raw,value=${{ matrix.label_prefix }}-{{sha}}
            type=raw,value=${{ matrix.label_prefix }}-{{date 'YYYY-MM-DD'}}
            type=raw,value=${{ matrix.label_prefix }}-latest
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: build
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
          context: devcontainer/${{ matrix.arch }}
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
