on:
  push:
    branches:
      - 'master'
    paths:
      - 'macos/**'
  pull_request:
    branches:
      - 'master'
    paths:
      - 'macos/**'

jobs:
  build:
    name: Build & deploy ``macOS`` images
    strategy:
      fail-fast: false
      matrix:
        include:
          - { version: arm64, arch: arm64, runner: macos-15, jobs: 3, prefix: /opt/homebrew, cxxflags: "-O2 -g -march=armv8.5a -fPIC -DPIC", deployment_target: "14.0" }
    runs-on: ${{ matrix.runner }}
    env:
      JOBS: ${{ matrix.jobs }}
      DESTDIR: /tmp/DESTDIR
      OUTPUTDIR: /tmp/OUTPUT
      PREFIX: ${{ matrix.prefix }}
      PYTHON_VERSIONS: "3.12 3.13 3.14"
      CFLAGS: ${{ matrix.cxxflags }}
      CXXFLAGS: ${{ matrix.cxxflags }}
      MACOSX_DEPLOYMENT_TARGET: ${{ matrix.deployment_target }}
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Install build dependencies and workflow dependencies
        shell: bash
        run: |
          brew install \
            autoconf automake cmake gnu-sed libtool m4 make pkg-config \
            oras
      -
        name: Create directories
        shell: bash
        run: |
          mkdir -p ${DESTDIR}
          mkdir -p ${OUTPUTDIR}
      -
        name: Build yaml-cpp
        shell: bash
        run: ./macos/${{ matrix.version }}/build-yaml-cpp.bash
      -
        name: Build GSL
        shell: bash
        run: ./macos/${{ matrix.version }}/build-gsl.bash
      -
        name: Build FFTW3
        shell: bash
        run: ./macos/${{ matrix.version }}/build-fftw3.bash
      -
        name: Build Boost
        shell: bash
        run: ./macos/${{ matrix.version }}/build-boost.bash
      -
        name: Create tarball
        shell: bash
        run: |
          cd ${DESTDIR}
          tar zcf ${OUTPUTDIR}/macos-${{ matrix.version }}.tar.gz *
      -
        name: Push tarball to ghcr.io
        shell: bash
        run: |
          oras login --username "${{ github.actor }}" --password "${{ secrets.GITHUB_TOKEN }}" ghcr.io
          cd ${OUTPUTDIR}
          oras push \
            ghcr.io/eos/docker.io:macos-${{ matrix.version }}-${GITHUB_SHA::7} \
            -a "org.opencontainers.image.source=https://github.com/eos/docker.io" \
            macos-${{ matrix.version }}.tar.gz
